spring.application.name=backend-resume

# MongoDB - change URI if using MongoDB Atlas
spring.data.mongodb.uri=${MONGO_URL}
server.port=${PORT:8080}
# Server port


# Allow CORS (handled in controller, this is just info)
# Frontend runs at http://localhost:5173
