spring.application.name=backend-resume

# MongoDB - change URI if using MongoDB Atlas
spring.data.mongodb.uri=mongodb://localhost:27017/resumedb

# Server port
server.port=8080

# Allow CORS (handled in controller, this is just info)
# Frontend runs at http://localhost:5173
